version: "3"

networks:
  net0:
    driver: overlay

services:

  zilla:
    image: "ghcr.io/aklivity/zilla:latest"
    hostname: "zilla.internal.net"
    command: [ "start", "-v", "-e", "-c", "file:/etc/zilla/zilla.json" ]
    volumes:
      - ./zilla.json:/etc/zilla/zilla.json:ro
      - ./localhost.p12:/etc/zilla/ssl/localhost.p12:ro
      - ./truststore.p12:/etc/zilla/ssl//truststore.p12:ro
    networks:
      - net0
    ports:
      - "8080:8080"
      - "9090:9090"

  nginx:
    image: "nginx:latest"
    hostname: "nginx.internal.net"
    tty: true
    volumes:
      - ./server/cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./server/key.pem:/etc/nginx/ssl/key.pem:ro
      - ./server/demo.html:/usr/share/nginx/html/demo.html:ro
      - ./server/style.css:/usr/share/nginx/html/style.css:ro
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - net0
    ports:
      - "443:443"
