env:
  MOSQUITTO_BROKER_HOST: mosquitto
  MOSQUITTO_BROKER_PORT: "1883"
  ZILLA_INCUBATOR_ENABLED: "true"

livenessProbePort: 7183
readinessProbePort: 7183

service:
  ports:
    - port: 7183
      name: mqtt
