name: ${NAMESPACE:-zilla-openapi-asyncapi-proxy}
services:
  zilla:
    image: ghcr.io/aklivity/zilla:${ZILLA_VERSION:-latest}
    pull_policy: always
    restart: unless-stopped
    ports:
      - 7114:7114
    environment:
      ENV: env
    volumes:
      - ./zilla.yaml:/etc/zilla/zilla.yaml
    command: start -v -e

networks:
  default:
    driver: bridge
