version: "3"

networks:
  net0:
    driver: overlay

services:

  zilla:
    image: "ghcr.io/aklivity/zilla:latest"
    hostname: "zilla"
    command: [ "start", "-v", "-e", "-c", "file:/etc/zilla/zilla.json" ]
    volumes:
      - ./zilla.json:/etc/zilla/zilla.json:ro
      - ./localhost.p12:/etc/zilla/ssl/localhost.p12:ro
      - ./web:/var/www:ro
    networks:
      - net0
    ports:
      - "8080:8080"
      - "9090:9090"
