version: '3'
services:
  zilla:
    image: ghcr.io/aklivity/zilla
    container_name: zilla
    pull_policy: always
    restart: unless-stopped
    ports:
      - 7183:7183
      - 5005:5005
    environment:
      KEYSTORE_PASSWORD: generated
      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}
      ZILLA_INCUBATOR_ENABLED: "true"
      JAVA_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005
    volumes:
      - ../../zilla.yaml:/etc/zilla/zilla.yaml
    command: start -v -e

networks:
  default:
    driver: bridge
