args: ["start", "-v", "-e", "-P", "zilla.binding.kafka.client.connection.pool=false"]

env:
  - name: KEYSTORE_PASSWORD
    value: generated

livenessProbePort: 7183
readinessProbePort: 7183

service:
  ports:
    - port: 7183
      name: mqtt
    - port: 8883
      name: mqtts
