replicaCount: 2

resources:
  requests:
    memory: 512Mi
    cpu: 500m

yamlApplicationConfig:
  kafka:
    clusters:
      - name: kafka
        bootstrapServers: kafka.grpc-proxy.svc.cluster.local:9092
        readOnly: true
        properties:
          security.protocol: SASL_SSL
          sasl.mechanism: PLAIN
          sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin";
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
ingress:
  enabled: true
  ingressClassName: nginx
  # host: quickstart.aklivity.io
  path: /kafka
  # tls:
  #   enabled: true
  #   secretName: quickstart-tls
envs:
  config:
    SERVER_SERVLET_CONTEXT_PATH: /kafka

existingSecret: "deploy-secrets"
