replicaCount: 3

image:
  repository: ghcr.io/aklivity/zilla
  tag: "0.9.87"

args: ["start", "-v", "-e", "-Pzilla.engine.worker.capacity=512", "-Pzilla.binding.kafka.client.group.min.session.timeout.default=30000"]

env:
  ROUTE_GUIDE_SERVER_HOST: "route-guide.zilla.svc.cluster.local"
  ROUTE_GUIDE_SERVER_PORT: "50051"
  ZILLA_INCUBATOR_ENABLED: "true"

livenessProbePort: prometheus
readinessProbePort: prometheus

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: '*'
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
  # host: ""
  paths:
    - path: /api
      pathType: Prefix
      port: 7114
  tls:
    enabled: false
  #   secretName: quickstart-tls

resources:
  requests:
    memory: 512Mi
    cpu: 1000m

service:
  ports:
    - port: 7114
      name: http
    - port: 7183
      name: mqtt
    - port: 7151
      name: grpc
    - port: 7190
      name: prometheus

envFromSecret: "deploy-secrets"

volumeMounts:
  - name: proto-files
    mountPath: /proto

volumes:
  - name: proto-files
    configMap:
      name: protobuf-files
