replicaCount: 1

image:
  repository: ghcr.io/aklivity/zilla
  tag: "0.9.84"

args: ["start", "-v", "-e", "-Pzilla.engine.worker.capacity=512", "-Pzilla.binding.kafka.client.connection.pool=false"]

env:
  ROUTE_GUIDE_SERVER_HOST: "route-guide.zilla.svc.cluster.local"
  ROUTE_GUIDE_SERVER_PORT: "50051"
  ZILLA_INCUBATOR_ENABLED: "true"
  # JAVA_OPTIONS: "-Dzilla.binding.kafka.debug=true -Djavax.net.debug=ssl,handshake"

livenessProbePort: prometheus
readinessProbePort: prometheus

ingress:
  enabled: true
  ingressClassName: nginx
  # host: ""
  paths:
    - path: /api
      pathType: Prefix
      port: 7114
  tls:
    enabled: false
  #   secretName: quickstart-tls

service:
  ports:
    - port: 7114
      name: http
    - port: 7183
      name: mqtt
    - port: 7151
      name: grpc
    - port: 7190
      name: prometheus

envFromSecret: "deploy-secrets"

volumeMounts:
 - name: proto-files
   mountPath: /proto

volumes:
 - name: proto-files
   configMap:
     name: protobuf-files
