name: ${NAMESPACE:-zilla-grpc-echo}
services:
  zilla:
    image: ghcr.io/aklivity/zilla:${ZILLA_VERSION:-latest}
    restart: unless-stopped
    ports:
      - 7151:7151
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 5
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/7151"]
    volumes:
      - ./zilla.yaml:/etc/zilla/zilla.yaml
      - ./echo.proto:/etc/zilla/protos/echo.proto
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: start -v -e

networks:
  default:
    driver: bridge
