version: "3"

networks:
  net0:
    driver: overlay

services:

  zilla:
    image: "ghcr.io/aklivity/zilla:develop-SNAPSHOT"
    hostname: "zilla.internal.net"
    command: [ "start", "-v", "-e" ]
    volumes:
      - ./zilla.json:/zilla.json:ro
      - ./localhost.p12:/localhost.p12:ro
      - ./truststore.p12:/truststore.p12:ro
    networks:
      - net0
    ports:
      - "8080:8080"
      - "9090:9090"

  http2:
    image: "nginx:latest"
    hostname: "http2.internal.net"
    tty: true
    volumes:
      - ./server/cert.pem:/ssl/cert.pem:ro
      - ./server/key.pem:/ssl/key.pem:ro
      - ./server/demo.html:/usr/share/nginx/html/demo.html:ro
      - ./server/style.css:/usr/share/nginx/html/style.css:ro
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - net0
    ports:
      - "443:443"
