initContainers:
  - name: wait-for-zilla-config-server
    image: "busybox:latest"
    command: ['/bin/sh', '-c', 'until nc -w 2 zilla-config-server-config 7115; do echo . && sleep 5; done']

env:
  - name: KEYSTORE_PASSWORD
    value: generated

args: ["start", "-v", "-e", "-p", "/etc/zilla/prop/zilla.properties"]

livenessProbePort: 7114
readinessProbePort: 7114

service:
  ports:
    - port: 7114
      name: http
    - port: 7143
      name: https

zilla.yaml: ""
