name: ${NAMESPACE:-zilla-openapi-proxy}
services:
  zilla:
    image: ghcr.io/aklivity/zilla:${ZILLA_VERSION:-latest}
    pull_policy: always
    restart: unless-stopped
    ports:
      - 7114:7114
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 5
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/7114"]
    volumes:
      - ./specs/petstore.yaml:/etc/zilla/petstore.yaml
      - ./zilla.yaml:/etc/zilla/zilla.yaml
    command: start -v -e

  openapi-mock:
    image: jormaechea/open-api-mocker:2.0.0
    container_name: openapi-mock
    volumes:
      - ./specs:/app
    ports:
      - "8000:5000"
    command: open-api-mocker -s /app/petstore.yaml

networks:
  default:
    driver: bridge
