version: "3"

networks:
  net0:
    driver: overlay

services:

  zilla:
    image: "ghcr.io/aklivity/zilla:develop-SNAPSHOT"
    hostname: "zilla"
    command: [ "start", "-v", "-e", "-c", "file:/etc/zilla/zilla.json" ]
    volumes:
      - ./zilla.json:/etc/zilla/zilla.json:ro
      - ./localhost.p12:/etc/zilla/ssl/localhost.p12:ro
    networks:
      - net0
    ports:
      - "1883:1883"
      - "8883:8883"
