extraEnv:
  - name: SSE_SERVER_HOST
    value: sse-server
  - name: SSE_SERVER_PORT
    value: "8001"
  - name: KEYSTORE_PASSWORD
    value: generated
  - name: ZILLA_INCUBATOR_ENABLED
    value: "true"

livenessProbePort: 7114
readinessProbePort: 7114

service:
  ports:
    - port: 7114
      name: http
