name: Reusable Workflow for running tests

on:
  workflow_dispatch:
    inputs:
      example-dir:
        required: true
        description: Directory name for the example to test
        type: string
      
  workflow_call:
    inputs:
      example-dir:
        required: true
        type: string


jobs:

  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        working-directory: ${{ inputs.example-dir }}
        run: ./setup.sh
      - name: Wait for Zilla to be healthy
        working-directory: ${{ inputs.example-dir }}
        run: timeout 60s sh -c 'until docker compose ps zilla --format "{{.Name}} {{.Health}}" | grep -q healthy; do echo "Waiting for container to be healthy..."; sleep 2; done'
      - name: Execute Test
        working-directory: ${{ inputs.example-dir }}
        run: |
          set -o pipefail
          ./test.sh | tee $GITHUB_STEP_SUMMARY

      - name: Collect docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          dest: './logs'
      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs.tgz ./logs
      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs.tgz
          path: ./logs.tgz

      - name: Teardown
        if: always()
        working-directory: ${{ inputs.example-dir }}
        run: ./teardown.sh
