name: Test Examples

on:
  pull_request:
  workflow_dispatch:

jobs:
  get-examples-dirs:
    runs-on: ubuntu-latest
    outputs:
      all_directories: ${{ steps.set-output.outputs.changed_directories }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List all example directories
        id: list-dirs
        uses: Drafteame/list-folders-action@main
        with:
          paths: .
          omit: |
            ^\.github$
            ^\.assets$
          separator: ","

      - name: "Set output in the matrix format"
        id: set-output
        run: echo "changed_directories=${{ steps.list-dirs.outputs.folders_no_base_path }}" >> "$GITHUB_OUTPUT"

  testing:
    runs-on: ubuntu-latest
    needs: get-examples-dirs
    strategy:
      matrix:
        dir: ${{ fromJson(needs.get-examples-dirs.outputs.all_directories) }}
      fail-fast: false
    steps:
      - name: Run reusable test runner
        uses: ./.github/workflows/reusable_test_runner.yaml
        with:
          example-dir: ${{ matrix.dir }}
