name: Test Examples

on:
  pull_request:
  workflow_dispatch:

jobs:
  list-examples-dirs:
    name: List Example Directories
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.list-dirs.outputs.folders }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List all example directories
        id: list-dirs
        uses: philips-labs/list-folders-action@v1
        with:
          path: .
          exclude: |
            .github
            .assets

  testing:
    runs-on: ubuntu-latest
    needs: list-examples-dirs
    strategy:
      matrix:
        folder: ${{ fromJson(needs.list-examples-dirs.outputs.folders) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ matrix.folder }}

      - name: Run reusable test runner
        uses: ./.github/workflows/reusable_test_runner.yaml
        with:
          example-dir: ${{ matrix.folder }}
