name: Test Examples

on:
  pull_request:
  workflow_dispatch:

jobs:
  get-examples-dirs:
    runs-on: ubuntu-latest
    outputs:
      all_directories: ${{ steps.all-files.outputs.folders }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get examples dirs
        id: all-files
        uses: philips-labs/list-folders-action@v1
        with:
          path: .

  testing:
    strategy:
      matrix: ${{fromJson(needs.get-examples-dirs.outputs.all_directories)}}
      fail-fast: false
    needs:
      - get-examples-dirs
    uses: ./.github/workflows/reusable_test_runner.yaml
    with:
      example-dir: ${{ matrix.dir }}
