name: Test Examples

on:
  pull_request:
  workflow_dispatch:

jobs:
  get-examples-dirs:
    runs-on: ubuntu-latest
    outputs:
      all_directories: ${{ steps.list-dirs.outputs.folders_no_base_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List all example directories
        id: list-dirs
        uses: Drafteame/list-folders-action@main
        with:
          paths: .
          omit: |
            ^\.github$
            ^\.assets$
          separator: ","

  testing:
    runs-on: ubuntu-latest
    needs: get-examples-dirs
    strategy:
      matrix:
        dir: ${{ fromJson(needs.get-examples-dirs.outputs.all_directories) }}
      fail-fast: false
    uses: ./.github/workflows/reusable_test_runner.yaml
    with:
      example-dir: ${{ matrix.dir }}
