name: Test Examples

on:
  pull_request:
  workflow_dispatch:

jobs:
  get-examples-dirs:
    runs-on: ubuntu-latest
    outputs:
      all_directories: ${{ steps.all-files.outputs.folders_no_base_path }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get examples dirs
        id: all-files
        uses: Drafteame/list-folders-action@main
        with:
          paths: |
            .
          omit: |
            ^\.github$
            ^\.assets$
            ^\.git$
            ^\.vscode$

      - name: Debug output
        run: echo "all_directories=${{ steps.all-files.outputs.folders_no_base_path }}"

  testing:
    strategy:
      matrix:
        dir: [amqp.reflect,asyncapi.http.kafka.proxy,asyncapi.mqtt.kafka.proxy,asyncapi.mqtt.proxy,asyncapi.sse.kafka.proxy,asyncapi.sse.proxy,grpc.echo,grpc.kafka.echo,grpc.kafka.fanout,grpc.kafka.proxy,grpc.proxy,http.filesystem,http.json.schema,http.kafka.async,http.kafka.avro.json,http.kafka.cache,http.kafka.crud,http.kafka.oneway,http.kafka.proto.json,http.kafka.proto.oneway,http.kafka.sync,http.proxy,http.proxy.jwt,mqtt.kafka.proxy,mqtt.proxy.jwt,openapi.asyncapi.kakfa.proxy,openapi.proxy,sse.jwt,sse.kafka.fanout,tcp.echo,tcp.reflect,tls.echo,tls.reflect,ws.echo,ws.reflect]
      fail-fast: false
    needs:
      - get-examples-dirs
    uses: ./.github/workflows/reusable_test_runner.yaml
    with:
      example-dir: ${{ matrix.dir }}
