name: Test Examples

on:
  pull_request:
  workflow_dispatch:

jobs:
  get-examples-dirs:
    runs-on: ubuntu-latest
    outputs:
      all_directories: ${{ steps.all-files.outputs.folders_no_base_path }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get examples dirs
        id: all-files
        uses: Drafteame/list-folders-action@main
        with:
          paths: |
            .
          omit: |
            ^\.github$
            ^\.assets$
            ^\.git$
            ^\.vscode$

      - name: Debug output
        run: echo "all_directories=${{ steps.all-files.outputs.folders_no_base_path }}"

  testing:
    strategy:
      matrix:
        dir: ["amqp.reflect","asyncapi.http.kafka.proxy"]
      fail-fast: false
    needs:
      - get-examples-dirs
    uses: ./.github/workflows/reusable_test_runner.yaml
    with:
      example-dir: ${{ matrix.dir }}
